build:
    dotnet build
clean:
    dotnet clean
restore:
    dotnet restore
watch:
    dotnet watch --project .\Masya.TelegramBot.Api\Masya.TelegramBot.Api.csproj run
start:
    dotnet run --project .\Masya.TelegramBot.Api\Masya.TelegramBot.Api.csproj